name = "yjs-workers"
main = "src/e2e/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags=["nodejs_compat"]

[[durable_objects.bindings]]
name = "Y_DURABLE_OBJECTS"
class_name = "YDurableObjects"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["YDurableObjects"]

