name = "yjs-workers"
main = "./src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags=["nodejs_compat"]

[[durable_objects.bindings]]
name = "Y_DURABLE_OBJECTS"
class_name = "YDurableObjects"

[[migrations]]
tag = "v1"
new_classes = ["YDurableObjects"]

