name = "workers"
compatibility_date = "2023-01-01"
workers_dev=false
main="src/index.ts"

[[durable_objects.bindings]]
name = "YJS_PROVIDER"
class_name = "YjsProvider"

[[migrations]]
tag = "v1"
new_classes = ["YjsProvider"]