name = "yjs-workers"
compatibility_date = "2024-04-03"
workers_dev=false
main="src/index.ts"

[[durable_objects.bindings]]
name = "Y_DURABLE_OBJECTS"
class_name = "YDurableObjects"

[[migrations]]
tag = "v1"
new_classes = ["YjsProvider"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "YjsProvider", to = "YWebsocket" }]

[[migrations]]
tag = "v3"
renamed_classes = [{ from = "YWebsocket", to = "YDurableObjects" }]
